### ISSUE TITLE
Current exhibition - content

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#55]
there's no place in the CMS to show the essential content of current exhibition like key visual,  date, time etc 
https://docs.google.com/spreadsheets/d/1gqQEWke4YeGxoNJYizb2iBFgU_RtUEJndKoVU9DJUYQ/edit#gid=0
![image](https://user-images.githubusercontent.com/95728978/225900925-4ff9f635-67f6-4a76-9ce7-ebdc113023ce.png)

**Comment by shibacomputer** [comment]
## Proposal for the rebuilt Current / Previous Exhibitions page

This is a short proposal that covers the refactor of the Current Exhibition Page. We're doing this because although the page functionality matches the desired functionality presented by WMA, this is not clear to the CMS team. The majority of this functionality is automated, but the invisibility of the automation PLUS the existing UX for authoring the Current Exhibition page has consistently resulted in the team struggling to understand what the page is doing, and to try to misuse/reuse available text boxes, etc to achieve their goals.

## Solution:
### 1. Make the Current Exhibition page completely dynamic 
In the CMS, the Current Exhibition page will be authored by inserting Compoments, similar to how the Landing Page is authored:
![image](https://github.com/newdesigncongress/wma-hk-web/assets/737950/0a77b238-f729-43aa-b141-124d69f1e15d)

### 2. Replace the Current Exhibition section AND the Past Exhibition sections with completely automated Components
The Current Exhibition and Past Exhibition will become Components that will be available to CMS Authors in the Current Exhibition Page and selected in a list similar to this screenshot:
![image](https://github.com/newdesigncongress/wma-hk-web/assets/737950/f92530fc-76e5-4e8a-9653-4d8ee0660ea6)
These blocks will have no editible properties. When inserted into the page, they behave as small automated "widgets" that query Events, Exhibitions, Artworks etc and automatically display forthcoming, current or past exhibitions without any intervention needed from the team.  

### 2. More flexibility with Content Blocks
Similar to the screenshot above (pasted here again for reference):
![image](https://github.com/newdesigncongress/wma-hk-web/assets/737950/655fdb40-6cef-4522-ad39-bc6ee5d9e278)
CMS authors will have access to a collection of other components that they can build the page with, including: Collaborator Blocks, Rich Text Blocks, etc. This means the team can author whatever content they will need around the automatic Current and Previous Exhibition widgets

### 3. Move all labels into the global dictionary
To reduce confusion, the labels and titles for the Current Exhibition page - including text that communicates that there are no Current Exhibitions, will be moved to the Global Translation Items, similar to how things like Day of the Week, etc are translated. 

### 4. Create start / close date offset rules for the automated Exhibition widgets
Exhibitions that are upcoming will be visible on the Current Exhibition page, and recently ended Exhibitions will still be promoted for a set amount of time as determined by the team (eg, 48hours after exhibition closure)  to maximise exhibition visibility.

I hope that makes sense! Comments appreciated!

**Comment by ClauLung** [comment]
agreed 3&4 
but for the dynamic content blocks, the components list does not fit the information that we'd like to show on this page, in order words, we don't need information of past exhibition, and would like to show key visuals, installation shots, curatorial statements, exhibition details (venue, time & date, register link), artist's bio, recording of talks & guided tours etc.

**Comment by shibacomputer** [comment]
Update:
"Creating HK page" to be replaced with a dynamic link to the currently active event

**Comment by ClauLung** [comment]
havn't seen in CMS, let's keep it open until we see it in CMS

**Comment by shibacomputer** [comment]
What's missing in the CMS?

**Comment by ClauLung** [comment]
right now, all the fields in CMS won't be shown in front end, so we could remove them as we will directly link the events to the page, but one thing could like to edit is the header and the title 
<img width="918" alt="Screenshot 2023-09-06 at 9 35 42 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/cb1bd3c3-00b7-4f67-9aac-03696b9fc412">

**Comment by shibacomputer** [comment]
We've pulled the obsolute items from the CMS locally and will close this once we've updated the production CMS.

**Comment by shibacomputer** [comment]
We need to open a new ticket for the title, but I don't consider this a blocker for user testing
